### PR TITLE
URL parameter placeholders in graph definitions

### PR DESCRIPTION
**Pull request by bwhaley**
This lets us call something like
    `http://graphite.example.net/system/common/details/cpu/?p[node]=somenode.example.net`

And refer to that node in the graph definitions like so
    `:data  => "servers.%{node}.cpu*.cpu-wait.value"`

This PR inspired by tanelj/gdash@0b4560900.

### CODE REVIEW

**Comment by keymon** [comment]
I will try this one soon. I like the idea, and based on this we can create "dynamic dashboards". The idea is that in a dashboard configuration you can specify some properties that can be set by the user from the frontend, for example:

:dynamic_properties:
  :server: 
    :type: "input"
    :default: "server1.example.net"
  :operations:
    :type: "multiselect"
    :values: [ "delete", "create", "update" ]
    :default: [ "update" ]

Then in the top of the dashboard we can build a small form to change these properties

**Comment by falkenbt** [comment]
:+1: 
I really like the idea of gdash becoming more interactive.

**Comment by falkenbt** [comment]
For some reason this does not work for me. %{node} is not being replaced in the resulting URL. 
(I did update graphite_graph to 0.0.8.)

**Comment by bwhaley** [comment]
Could you paste exactly the URL you are trying (sanitized if necessary, obviously) and the :data line from your graph definition?

**Comment by falkenbt** [comment]
graph:

```
:data  => "machines.*.%{node}.cpu.user"    
```

url:

```
http://localhost:8090/Zdev/include/?p[node]=myserver    
```

Resulting graphite URL:

```
target=machines.*.%25{node}.cpu.user"    
```

**Comment by keymon** [comment]
Try using a # , not a %... 
  :data  => "machines.*.#{node}.cpu.user"

**Comment by bwhaley** [comment]
Should be % actually. From line 359 of graphite_graph.rb:

`properties[:placeholders].each { |k,v| url_parts.each {|part| part.gsub!("%{#{k}}", v.to_s) } } if properties[:placeholders].is_a?(Hash)`

I'm assuming you've done the basics like restarting your HTTP server to ensure the correct version of the graphite-graph-dsl gem is loaded. I had problems with this at first as well, even using shotgun.

**Comment by falkenbt** [comment]
I guessed it should be a #, but that did not work either, it throws an NameError ('node' is unknown). 
I've uninstalled and reinstalled graphite-graph-dsl. Still no luck. I keep searching...

**Comment by bwhaley** [comment]
I'm stumped then. This works for me:

`http://localhost:8000/system/common/?p[node]=myserver_fq_dn`

and in my graph:

`:data  => "sumSeries(derivative(servers.%{node}.cpu-*.cpu-wait.value))"`

Tested against master. Has anyone other than me tested this successfully? My bad, I thought the earlier comments and  :+1: meant it was tested and working for others.

**Pull request merged**
