### PR TITLE
Added a "Print this page" functionality

### PR DESCRIPTION
**Pull request by keymon**
I like the graphs be white on black on my screen... but in some cases I want to print the page, and the ink is more expensive than my own blood.

The Print this page feature will create a black on white version of the current page, and open the print dialog, removing unnecessary headers.

You can also create some custom properties to use in printing mode.

Note: Requires and includes PR #68

### CODE REVIEW

**Comment by falkenbt** [comment]
:+1: 
works like a charm. 
Lets merge?

**Comment by falkenbt** [comment]
Ah,  too late, automatic merge not working anymore. Wanna check?

**Comment by keymon** [comment]
I will tonight

**Comment by keymon** [comment]
Please, try now. There were some conflicts with the placeholder pull.

**Comment by chjohnst** [comment]
Nevermind!

**Comment by keymon** [comment]
I will merge this functionality

**Comment by bwhaley** [comment]
This broke gdash with ruby 1.8.7. I was able to work around it with rvm. I know 1.8.7 is old, but lots of Linux distributions still use it by default. Do we need to preserve 1.8.7 compatibility?

See gist - https://gist.github.com/bwhaley/4772872

**Comment by keymon** [comment]
checking

**Pull request merged**
