### PR TITLE
Don't use decode_www_form that is not supported on ruby 1.8.7

### PR DESCRIPTION
**Pull request by keymon**
Trying to fix #69 on ruby 1.8.7

### CODE REVIEW

**Comment by keymon** [comment]
@falkenbt Can you try this implementation? My RVM installation has problems and I was not able to test in 1.8.7

**Comment by bwhaley** [comment]
+1 this fixed with 1.8.7 for me.

**Comment by keymon** [comment]
I don't understand why ruby does not include a proper function to regenerate the query parameters in the url.

**Comment by bwhaley** [comment]
Thanks for the quick fix, keymon.

**Pull request merged**
