### PR TITLE
Quick interval period filters and option to set graph dimensions and interval with url or dasboard config file

### PR DESCRIPTION
**Pull request by tanelj**
I have added options to set the graph dimensions or interval period with url (inspirited by nathan-opscode  https://github.com/ripienaar/gdash/pull/14 commits).

Eg:

```
http://gdash.example.com/dashboard/email/?from=-8d&until=-7d
http://gdash.example.com/dashboard/email/full/2/600/300?from=-8d&until=-7d
http://gdash.example.com/dashboard/email/full/4?width=600&height=300&from=-8d&until=-7d
```

There is also a optional configurable interval quick filter for dashboards.

Also dashboard based default dimension and interval settings are configurable via dashboard _dash.yml_ file.

### CODE REVIEW

**Comment by blysik** [comment]
This doesn't appear to work for the this route:

```
get '/:category/:dash/?*' do
```

Looking through the code, I don't see how 
   options[:width] ||= @width
   options[:height] ||= @height
get set at all in that route.

Shouldn't you do something like, if no url  options, do:
        options[:width] = @graph_width
        options[:height] = @graph_height

?

**Comment by blysik** [comment]
Ignore me please.  Found my error.

**Comment by nstielau** [comment]
This looks good to me, love to see it merged.

**Comment by joemiller** [comment]
I like this too. +1

**Comment by ripienaar** [comment]
I have rebased and merged this request, really sorry for the delay in this

**Pull request closed without merging**
