### PR TITLE
Support which properties use to sort the dashboards

### PR DESCRIPTION
**Pull request by keymon**
You can use: 

   :sort_dashboards_by: [ link, name ]

in the config/gdash.yaml to change the sorting criteria. Defaults to [ name ], as before.

### CODE REVIEW

**Comment by keymon** [comment]
I added logic to specify the order criteria for the dashboard graphs aswell. Right now it is based on the file name, but you can use the name, description... also any property using properties[:key] = value in the graph definition.

This is cool, because you can add to you graphs something like this to force some order:

   properties[:weight] = 10

**Comment by keymon** [comment]
Are you guys happy with this PR? I would like to merge it.

**Comment by falkenbt** [comment]
Can you update this so we can merge?

**Comment by forest** [comment]
:+1:

**Pull request closed without merging**
