### PR TITLE
Added prefix option to search

### PR DESCRIPTION
**Pull request by tubit**
Hi,

the search functionality missed the "prefix" option. So if the app was not installed at root level, search was broken.

This commit is going to fix this.

Cheers
Dennis

### CODE REVIEW

**Comment by keymon** [comment]
Does the prefix work at all?

**Comment by tubit** [comment]
It's working, yes. Why?

**Comment by keymon** [comment]
https://github.com/ripienaar/gdash/issues/56 Last time I tested it failed for me.

**Comment by tubit** [comment]
I'll have a closer look tomorrow.

**Comment by tubit** [comment]
See my comment in https://github.com/ripienaar/gdash/issues/56

**Comment by keymon** [comment]
Thx.
Seems OK for me!

+1

**Comment by falkenbt** [comment]
+1

**Pull request merged**
